FROM nvidia/cuda:12.8.0-devel-ubuntu24.04


ARG DEBIAN_FRONTEND=noninteractive
ARG NPROC=4


WORKDIR /root


RUN apt-get update && apt-get install -y --no-install-recommends apt-utils && \
    apt-get install -y \
    wget unzip zip tar vim curl \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    libglm-dev libglfw3-dev \
    libeigen3-dev \
    libvtk9-dev libgtk-3-dev libcanberra-gtk-module libcanberra-gtk3-module 

RUN apt-get update && apt-get install -y libatlas-base-dev gfortran \
    libparmetis-dev \
    libtbb-dev \
    software-properties-common \
    git \
    gdb \
    sudo \
    cmake \
    gnuplot gnuplot-x11 \
    build-essential \
    python3-pip \
    libgtest-dev \
    libassimp-dev \
    libspdlog-dev \
    libfmt-dev \
    libopencv-contrib-dev \
    libopencv-dev \
    libpcl-dev && \
    rm -rf /var/lib/apt/lists/*

# WORKDIR /root
# RUN wget https://cmake.org/files/v3.16/cmake-3.16.0.tar.gz
# RUN tar -zxvf cmake-3.16.0.tar.gz
# WORKDIR /root/cmake-3.16.0
# RUN ./bootstrap
# RUN make -j$(nproc) && make install


WORKDIR /root
RUN git clone https://github.com/alandefreitas/matplotplusplus.git
RUN cd matplotplusplus && git checkout tags/v1.2.2 && mkdir build
WORKDIR /root/matplotplusplus/build
RUN cmake .. -DCMAKE_CXX_FLAGS="-Wno-error=pedantic"\
    -DMATPLOTPP_BUILD_EXAMPLES=OFF                  \
    -DMATPLOTPP_BUILD_SHARED_LIBS=ON                \
    -DMATPLOTPP_BUILD_TESTS=OFF                     \
    -DCMAKE_BUILD_TYPE=Release            \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    && make -j$(NPROC) && make install


RUN apt-get update && apt-get install -y ninja-build \
      catch2 \
      libc++-dev libc++abi-dev \
      libgl-dev \
      libgl1-mesa-dev \
      libglew-dev \
      libavdevice-dev libavformat-dev libavcodec-dev libavutil-dev libswscale-dev libswresample-dev && \
      rm -rf /var/lib/apt/lists/*



WORKDIR /root
RUN git clone --recursive https://github.com/stevenlovegrove/Pangolin.git
RUN cd Pangolin && git checkout tags/v0.9.4 && mkdir build
WORKDIR /root/Pangolin
RUN ./scripts/install_prerequisites.sh recommended
WORKDIR /root/Pangolin/build
RUN cmake .. && make -j$(NPROC) && make install


WORKDIR /root
RUN git clone --recursive https://github.com/koide3/iridescence
RUN cd iridescence && mkdir build
WORKDIR /root/iridescence/build
RUN cmake .. -DCMAKE_INSTALL_PREFIX=/usr/local -DBUILD_EXAMPLES=ON && make -j$(NPROC) && make install
RUN sed -i '/add_library(Iridescence::Iridescence ALIAS Iridescence::iridescence)/d' /usr/local/lib/cmake/iridescence/iridescence-config.cmake



WORKDIR /root
