FROM nvidia/cuda:12.4.0-devel-ubuntu20.04


ARG DEBIAN_FRONTEND=noninteractive
ARG NPROC=4


WORKDIR /root


RUN apt-get update && apt-get install -y --no-install-recommends apt-utils && \
    apt-get install -y \
    wget unzip zip tar vim curl \
    libboost-all-dev \
    libjpeg-dev libpng-dev libtiff-dev \
    libeigen3-dev \
    libvtk7-dev libgtk-3-dev libcanberra-gtk-module libcanberra-gtk3-module 

RUN apt-get update && apt-get install -y libatlas-base-dev gfortran \
    libparmetis-dev \
    libtbb-dev \
    software-properties-common \
    git \
    gdb \
    gnuplot gnuplot-x11 \
    build-essential \
    python3-pip \
    libopencv-contrib-dev \
    libopencv-dev \
    libpcl-dev && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /root
RUN wget https://cmake.org/files/v3.16/cmake-3.16.0.tar.gz
RUN tar -zxvf cmake-3.16.0.tar.gz
WORKDIR /root/cmake-3.16.0
RUN ./bootstrap
RUN make -j$(nproc) && make install


WORKDIR /root
RUN git clone https://github.com/alandefreitas/matplotplusplus.git
RUN mkdir matplotplusplus/build
WORKDIR /root/matplotplusplus/build
RUN cmake .. -DCMAKE_CXX_FLAGS="-Wno-error=pedantic"\
    -DMATPLOTPP_BUILD_EXAMPLES=OFF                  \
    -DMATPLOTPP_BUILD_SHARED_LIBS=ON                \
    -DMATPLOTPP_BUILD_TESTS=OFF                     \
    -DCMAKE_BUILD_TYPE=Release            \
    -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=ON \
    && make -j$(NPROC) && make install

# optional
WORKDIR /root
RUN git clone --recursive https://github.com/stevenlovegrove/Pangolin.git
RUN cd Pangolin && git checkout tags/v0.6 && mkdir build
WORKDIR /root/Pangolin/build
RUN cmake .. && make -j$(NPROC) && make install


WORKDIR /root
