%YAML:1.0

system:
  num_used_camera: 1
  use_external_trajectory_id: 0
  is_use_GT_depth: 1
  maximum_traj: 300
  ref_pose_idx: 50
  # ref_pose_idx: 8
  ref_camera_idx: 0
  start_match_uv: [0, 0]
  tar_pose_start_idx: 50
  # tar_pose_start_idx: 8
  image_sequence_mode: forward_time_direction # option: forward_time_direction, backward_time_direction, full_time_direction, fixed_order_of_traj
  min_depth: 1.0
  max_depth: 100
  half_window_size: 5 # we only support odd size of window, like 3x3, 5x5, 7x7, 9x9 ...
  save_figure_path: /root/multi_view_stereo/figs
  debug_plot: 1

external_trajectory0:
  name: GT_pose
  world_coordinate: NED frame
  trajectory_path: /root/datasets2/tartan_air/gascola_sample_P001/P001/pose_left.txt  
  # trajectory_path: /root/datasets2/tartan_air/seasonsforest_winter_sample_P006/P006/pose_left.txt  
  # trajectory_path: /root/datasets2/tartan_air/seasonsforest_sample_P002/P002/pose_left.txt  
  is_all_cameras_in_same_traj_file: 0
  T_pose_cam0:
    - [0,0,1,0]
    - [1,0,0,0]
    - [0,1,0,0] 
    - [0, 0, 0, 1.0]
  T_pose_cam1:
    # - [0,   1.0, 0,   0]
    # - [0,   0,   1.0, 0]
    # - [1.0, 0,   0,   0.25] 
    # - [0,   0,   0,   1.0]
    - [0,   0., 1.,   0]
    - [1.0,   0,   0., 0.25]
    - [0, 1.0,   0,   0] 
    - [0,   0,   0,   1.0]

# external_trajectory0:
#   name: colmap
#   world_coordinate: camera frame
#   trajectory_path: /root/datasets2/colmap_datasets/BotanicGarden_1018_00_16/colmap_trajectory/traj.txt
#   is_all_cameras_in_same_traj_file: 1
#   T_pose_cam0:
#     - [1.0, 0, 0, 0]
#     - [0, 1.0, 0, 0]
#     - [0, 0, 1.0, 0] 
#     - [0, 0, 0, 1.0]
#   T_pose_cam1:
#     - [1.0, 0, 0, 0.25]
#     - [0, 1.0, 0, 0]
#     - [0, 0, 1.0, 0] 
#     - [0, 0, 0, 1.0]






cam0:
  name: camera0
  dir_path: /root/datasets2/tartan_air/gascola_sample_P001/P001/image_left
  # dir_path: /root/datasets2/tartan_air/seasonsforest_winter_sample_P006/P006/image_left
  # dir_path: /root/datasets2/tartan_air/seasonsforest_sample_P002/P002/image_left
  original_resolution: [640, 480] # width x height
  resolution: [640, 480] # width x height, don't larger than original resolution
  camera_model: pinhole
  original_intrinsics: [320, 320, 320, 240] #fx, fy, cu, cv
  distortion_model: radtan
  distortion_coeffs: [0,0,0,0] #k1,k2,p1,p2
  use_deeplearning_depth_id: 0
  DeepLearning_depth0: 
    name: Midas
    path: /root/datasets2/tartan_air/gascola_sample_P001/P001/depth_left_tiff/depth  
  DeepLearning_depth0: 
    name: DepthAnythingV2
    path: /media/spiderman/zhipeng_8t1/datasets/tartan_air/gascola_sample_P001/P001/DepthAnythingV2/image_left/normalized_inv_depth
  use_GT_depth_id: 0
  GT_depth0:
    name: depthmap
    path: /root/datasets2/tartan_air/gascola_sample_P001/P001/depth_left_tiff/depth
    # path: /root/datasets2/tartan_air/seasonsforest_winter_sample_P006/P006/depth_left_tiff/depth
    # path: /root/datasets2/tartan_air/seasonsforest_sample_P002/P002/depth_left_tiff/depth
    T_cam_pose:
      - [1.0,0,0,0]
      - [0,1.0,0,0]
      - [0,0,1.0,0] 
      - [0,0,0,1.0]

cam1:
  name: camera1
  dir_path: /root/datasets2/tartan_air/gascola_sample_P001/P001/image_right
  # dir_path: /root/datasets2/tartan_air/seasonsforest_winter_sample_P006/P006/image_right
  # dir_path: /root/datasets2/tartan_air/seasonsforest_sample_P002/P002/image_right
  original_resolution: [640, 480] # width x height
  resolution: [640, 480] # width x height, don't larger than original resolution
  camera_model: pinhole
  original_intrinsics: [320, 320, 320, 240] #fx, fy, cu, cv
  distortion_model: radtan
  distortion_coeffs: [0,0,0,0] #k1,k2,p1,p2
  use_GT_depth_id: 0
  GT_depth0:
    name: depthmap
    path: /root/datasets2/tartan_air/gascola_sample_P001/P001/depth_right_tiff/depth
    # path: /root/datasets2/tartan_air/seasonsforest_winter_sample_P006/P006/depth_right_tiff/depth
    # path: /root/datasets2/tartan_air/seasonsforest_sample_P002/P002/depth_right_tiff/depth
    T_cam_pose:
      - [1.0,0,0,0]
      - [0,1.0,0,0]
      - [0,0,1.0,0] 
      - [0,0,0,1.0]